### ISSUE TITLE
Destacar Números Fixos

### ISSUE THREAD

**Issue by paulojoseph** [paulojoseph/sudoku#12]
Destacar, com cores, os números fixos do tabuleiro, que não possam ser alterados.

**Comment by yuriageme** [comment]
![Captura de tela de 2021-09-21 17-28-23](https://user-images.githubusercontent.com/86323667/134243096-da404d68-3222-4103-8920-c8c17f4efbb0.png)

**Comment by yuriageme** [comment]
![SudokuIssue2](https://user-images.githubusercontent.com/86323667/134243392-84a6d33f-5b52-4b82-b640-ef68bcb017e6.png)

**Comment by yuriageme** [comment]
O padrão de cores é:
Azul negrito para os números fixos;
Preto/Cinza para os números válidos inseridos pelo usuário;
vermelho para os números inseridos pelo usuário que estejam repetidos.
