### ISSUE TITLE
Destacar Erro Número

### ISSUE THREAD

**Issue by paulojoseph** [paulojoseph/sudoku#13]
Destacar, com cores, o número que está impedindo outro de ser jogado.

**Comment by yuriageme** [comment]
![Captura de tela de 2021-09-21 17-28-23](https://user-images.githubusercontent.com/86323667/134242894-17865fad-9890-46f2-8548-64091b14535c.png)

**Comment by yuriageme** [comment]
Números repetidos serão destacados na cor vermelha
