### ISSUE TITLE
Remover Método que checa o preenchimento correto

### ISSUE THREAD

**Issue by paulojoseph** [paulojoseph/sudoku#14]
Remover o método criado para testar se o preenchimento está correto a cada input.

**Comment by yuriageme** [comment]
Método Resolver() removido da classe sudoku, permaneceram os métodos checarLinha(), checarColuna() e ChecarQuadrante(). Em ocorrência de números repetidos, o número fica destacado em vermelho, mas o usuário não é impedido de jogar.
